### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by vishalfloradev** [artifex404/csv-to-vcf#1]
Fatal error: Uncaught RuntimeException: SplFileObject::__construct(contacts.csv): failed to open stream: No such file or directory in D:\xampp\htdocs\phpvcf\csv-to-vcf\vendor\league\csv\src\AbstractCsv.php:271 Stack trace: #0 D:\xampp\htdocs\phpvcf\csv-to-vcf\vendor\league\csv\src\AbstractCsv.php(271): SplFileObject->__construct('contacts.csv', 'r+') #1 D:\xampp\htdocs\phpvcf\csv-to-vcf\vendor\league\csv\src\AbstractCsv.php(253): League\Csv\AbstractCsv->setIterator() #2 D:\xampp\htdocs\phpvcf\csv-to-vcf\csv-to-vcf.php(24): League\Csv\AbstractCsv->getIterator() #3 {main} thrown in D:\xampp\htdocs\phpvcf\csv-to-vcf\vendor\league\csv\src\AbstractCsv.php on line 271

**Comment by artifex404** [comment]
It tries to open and parse the file "contacts.csv". As in the project description:
> To convert your CSV file to a VCF file, copy your CSV file to the project and name it contacts.csv
